version: "3"
services:
  freqtrade: &freqtrade
    hostname: freqtrade
    image: freqtrade_freqtrade:latest
    build: .
    volumes:
      - ~/.freq/config.json:/freqtrade/config.json
      - ~/.freq/tradesv3.sqlite:/freqtrade/tradesv3.sqlite
    command: --dynamic-whitelist 150
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "30"
  dryrun:
    <<: *freqtrade
    volumes:
      - ~/.freq/dryrun_config.json:/freqtrade/config.json
      - ~/.freq/dryrun_tradesv3.sqlite:/freqtrade/tradesv3.dry_run.sqlite
    command: --dry-run-db --dynamic-whitelist 150
  test:
    <<: *freqtrade
    volumes:
      - ~/.freq/test_config.json:/freqtrade/config.json
    entrypoint: pytest
  backtest:
    <<: *freqtrade
    volumes:
      - ~/.freq/test_config.json:/freqtrade/config.json
    command: backtesting --realistic-simulation
